load("//crane:index.bzl", "crane")
load("//download:index.bzl", "download")
load("//gcloud:index.bzl", "gcloud", "gcloud_auth")
load("//run:index.bzl", "run")
load("//run_all:index.bzl", "run_all")
load("//run_if:index.bzl", "run_if")
